### ISSUE TITLE
Enhance SUTA list for recently communicated users

### ISSUE THREAD

**Issue by atbits** [swifiic/repo#12]
SUTA on startup should send a message to HUB, including its MAC, DTN ID and time.
SUTA should verify the received data and update the database accordingly. 
If MAC address is already initialized, put an error message on server.
If DTN ID is different, but MAC address matches, allow update.

As part of this Change - remove DTN-ID and MAC address from SOA App and Hub code.

**Comment by aarthi1992** [comment]
-> When User is getting created in SOA, initialize MAC address as"000000" and dtn Id as "xxxxxx" and save it in database.
-> When SUTA andi on start up sends its information about MAC,DTN ID,and time, check whether if the MAC ID is not initialized , then update MAC and DTN ID.
-> If MAC is already initialized for the DTN ID but the coming MAC info varies from the value in db, dont update(Some one is trying to hack)
->If DTN ID is different, but MAC address matches, allow update
In SOA as a part of Edit user have a button to reset the MAC Address and DTN Id, it means SOA will directly go to database and change those values to the default values for that user.

**Comment by aarthi1992** [comment]
Added two columns in User table.
-> alter table User add column MacAddress varchar(64);
->update table User set MacAddress='0000000';
->alter table User add column TimeOfLastUpdateFromApp datetime;

**Comment by aarthi1992** [comment]
SUTA Hub side changes are done. SOA Side changes are remaining.

**Comment by atbits** [comment]
Closing the bug for SUTA. SOA changes to be done as a new issue.
