### ISSUE TITLE
SUTA HUB- periodic message transmission

### ISSUE THREAD

**Issue by atbits** [swifiic/repo#13]
Presently the HUB code does not send the messages automatically; we need to type SEND. Adapt the logic as follows:
a. include ability to read settings/properties from a config file for HUB (password for MySQL etc.).
b. when a new node is noted or DTN id for a node is changed, SUTA should send updates.
c. every 8 hours (based on config file) send the list of users.
d. User list should be sorted on time of update / contact from SUTA for that specific user.
- Design changes
- DB needs a new filed for TimeOfLastUpdateFromApp from SUTA
- When SUTA Android app starts, it should sent Update Action (see  issue #12)
- SUTA hub should update the  TimeOfLastUpdateFromApp
- "Send" logic should request user list sorted on High-to-Low "TimeOfLastUpdateFromApp"
- Number of users should be limited based on config settings (say 100 as default settings)

**Comment by aarthi1992** [comment]
The following changes are fixed   (see issue #12)
DB needs a new filed for TimeOfLastUpdateFromApp from SUTA
When SUTA Android app starts, it should sent Update Action (see issue #12)
SUTA hub should update the TimeOfLastUpdateFromApp
Send  logic should request user list sorted on High-to-Low "TimeOfLastUpdateFromApp"

**Comment by atbits** [comment]
As part of periodic sending of messages - order/sequence should be maintained at Android App side.
E.g. update 63 is received and later update 61 or 62 are received. Ignore them. It could also be based on calendar time from Hub - i.e. not uptime - but wall clock time.
If the wall clock time reported by Hub is ahead of Android App by more than 24 hours - report this issue in logs (Exception Notification?)? In future we may even send back messages to hub capturing such errors.

**Comment by aarthi1992** [comment]
->SUTA Hub "Send" Functionality is removed. SUTA Hub will multicast the user details automatically every 'X' hours automatically. The value X can be determined from the properties file
